name: Build and Execute PYthon Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de PYthon
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installation des d√©pendances
      run: 
        pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic

    - name: Execution des tests
      run: 
        pytest