name: Build and Execute PYthon Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.10, 3.12]

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de PYthon
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installation des d√©pendances
      run: 
        pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic

    - name: Execution des tests
      run: 
        coverage run -m pytest --profile 
        coverage report -m